
services:
  # 1. API Service (Your Django App)
  web:
    build: .  
    container_name: carrental-web
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate_schemas --shared && gunicorn CarRentalService.wsgi:application --bind 0.0.0.0:8000 --workers 5"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - .:/usr/src/app 
    env_file:
      - .env 
    secrets:
      - django_secret_key
      - postgres_password
    depends_on:
      db:
        condition: service_healthy
    
  # 2. Database Service (Your PostgreSQL)
  db:
    container_name: carrental_postgres
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

# 3. Nginx Service(Reverse Proxy)
  nginx:
    image: nginx:stable-alpine
    container_name: carrental-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - web

#4. Docker Volumes
volumes:
  postgres_data:
  static_volume:
  media_volume:

secrets:
  django_secret_key:
    file: ./secrets/django_secret_key/django_secret_key.txt
  postgres_password:
    file: ./secrets/postgres_password/postgres_password.txt